### ISSUE TITLE
thinspace will stay at a break but not hairspace, is this intended ?

### ISSUE THREAD

**Issue by jfbu** [wilx/project-uspace#2]
it is a question really, because I didn't check Unicode specs, but github is lacking an interface for that,

THIN SPACE is defined as `\leavevmode\,\linebreak[0]`, hence if a break occurs at the penalty, the kern `\,` will stay at end of line. 
<strike>The break may also happen before the kern, then it will disappear at start of next line.</strike>

**edit**: correction, due to the penalty following the kern, no break can happen before the kern (I got confused: if the kern had been followed by some glue, a break could happen before the kern; but not with penalties). TeX will complain of an overfull horizontal box, the kern will hang their invisibly in the margin.

On the other hand the HAIR SPACE is simply a glue, hence will not stay at end of a line. Is it deliberate that the two differ ? (this example is not convincing see next posts)

``` latex
\documentclass{article}
\begin{document}

\begin{minipage}{\dimexpr 100pt+.16667em\relax}
\rule{100pt}{1pt}\,\linebreak[0]a

\rule{\linewidth}{1pt}

X\hrulefill X

\rule{\linewidth}{1pt}\rlap{\smash{\rule{0.1pt}{5\baselineskip}}}
\end{minipage}
\end{document}
```

![capture d ecran 2016-10-28 a 09 39 31](https://cloud.githubusercontent.com/assets/2589111/19798620/7ffd16fe-9cf2-11e6-9a55-2f101db9be9f.png)

**Comment by jfbu** [comment]
Perhaps this is more relevant, produces the same image and shows the phenomenon of the kern staying at end of line.

```
\begin{minipage}{\dimexpr 100pt+.16667em\relax}
\hrulefill\,\linebreak[0]

a

\rule{\linewidth}{1pt}

X\hrulefill X

\rule{\linewidth}{1pt}\rlap{\smash{\rule{0.1pt}{5\baselineskip}}}

\end{minipage}
```

**Comment by jfbu** [comment]
ok, perhaps a more convincing example

``` latex
\documentclass{article}
\begin{document}

\begin{minipage}{\dimexpr 100pt+.16667em\relax}
\rule{45pt}{1pt}\ \ \rule{45.2pt}{1pt}x\,\linebreak[0]y

\rule{\linewidth}{1pt}\rlap{\smash{\rule{0.1pt}{2\baselineskip}}}
\end{minipage}
\end{document}
```

![capture d ecran 2016-10-28 a 10 05 14](https://cloud.githubusercontent.com/assets/2589111/19799290/32dc54e4-9cf6-11e6-915e-97e8d0929cac.png)

and adding `\showoutput` and examining the log one sees the kern refused to disappear in a break. The space at middle of line was shrinked to allow the kern to stay without creating overfull box.

```
.....\hbox(4.30554+0.0)x101.66672, glue set - 0.965  <=== compressed glue
......\hbox(0.0+0.0)x0.0
......\hbox(1.0+0.0)x45.0
.......\rule(1.0+0.0)x45.0
......\glue 3.33333 plus 1.66666 minus 1.11111
......\glue 3.33333 plus 1.66666 minus 1.11111
......\hbox(1.0+0.0)x45.2
.......\rule(1.0+0.0)x45.2
......\OT1/cmr/m/n/10 x
......\kern 1.66672 <=== kern is here at end of line
......\penalty 0
......\glue(\rightskip) 0.0
```

**Comment by wilx** [comment]
Thank you for the bug report. I have pushed a fix for this that uses `\newunicodechar{ }{\leavevmode\linebreak[0]\,}` for THIN SPACE instead.

**Comment by jfbu** [comment]
and what about FIGURE SPACE and PUNCTUATION SPACE ?  the `\hphantom` creates boxes which do not allow breaks. Again, I know nothing about how Unicode defines the behaviour of those at end of lines... but perhaps a `\linebreak[0]` could be added too after the `\leavevmode`.

**Comment by jfbu** [comment]
about my last comment, perhaps wrong proposal: the box will be there at start of new line. For better uniformity with THIN SPACE the code would have to create a `\kern`,  not a box. Hence, not use `\hphantom`. But again, perhaps a FIGURE SPACE must always have in all circumstances the width of a figure, then having such a space at start of next line after a break is ok. No idea what's the thing to do.

**Comment by wilx** [comment]
> and what about FIGURE SPACE and PUNCTUATION SPACE ? the `\hphantom` creates boxes which do not allow breaks. Again, I know nothing about how Unicode defines the behaviour of those at end of lines... but perhaps a `\linebreak[0]` could be added too after the `\leavevmode`.

According to [Whitespace character - Wikipedia](https://en.wikipedia.org/wiki/Whitespace_character), FIGURE SPACE is not breakable space. However, I think you have a point with PUNCTUATION SPACE.

**Comment by wilx** [comment]
I have pushed https://github.com/wilx/project-uspace/commit/22f9ec7e68c00ed214391b0cd21cc4f8f7bd972a to fix the issue with PUNCTUATION SPACE.

**Comment by jfbu** [comment]
This whole matter is complicated because for some reason LaTeX implemented `\,` as `\kern`. But for example the `\hspace` ultimately does a `\hskip`. If we put `\leavevmode[0]` after an `\hspace` it is like `\allowbreak\hspace{...}`. But after a `\kern` there is no permutation hence it remains like  `\kern <dimen>\allowbreak` and not `\allowbreak\kern<dimen>`.

Notice that Plain TeX has a `\,` only for math mode. The `\,` of LaTeX works both in text and math mode. It does a `\thinspace` in text mode, but this `\thinspace` is `\kern .16667em`.

**Comment by wilx** [comment]
So I have made the change to use `\allowbreak`.

**Comment by wilx** [comment]
I think this is fixed now.
