### ISSUE TITLE
``\allowbreak``  expands faster than ``\linebreak[0]`` (but is not equivalent)

### ISSUE THREAD

**Issue by jfbu** [wilx/project-uspace#3]
You use `\linebreak[0]` (in horizontal mode always). This is essentially like `\allowbreak` but its effect is to examine if there was a skip before and to position the zero penalty before that skip not after. This is not equivalent:

``` latex
\documentclass{article}
\usepackage{color}
\begin{document}

%\tracingmacros1

\parindent0pt

\newbox\mybox
\setbox\mybox\hbox{xxxxx}

\hsize \wd\mybox


\rule{\hsize}{1pt}

x\hspace{\wd\mybox}\leavevmode\linebreak[0]\,y

x\hspace{\wd\mybox}\leavevmode\allowbreak\,y

\showoutput

\end{document}
```

![capture d ecran 2016-10-28 a 12 46 21](https://cloud.githubusercontent.com/assets/2589111/19804180/18c1feda-9d0d-11e6-9b24-31bdeaa9a096.png)

In the first line, TeX discards (in the sense of "does not position the break there") the penalty 0 after `x` because it would lead to a too much underfull line (I think). Thus there is then the big hspace but no break points after: there can't be a break at the `\,` (which is a kern) because it is not followed by glue. Hence we end up with the situation above.

In the second line, the penalty is after the big hspace and allows TeX to break the line there. We get an overfull first line due to the big hspace.

This being said, we see that complicated circumstances lead to different results, but the main point is that `\linebreak[0]` does much more processing than `\allowbreak` (which simply expands to `\penalty\z@`.) I this wonder if `\allowbreak` would not be better.

**Comment by jfbu** [comment]
A more interesting example:

``` latex
\documentclass{article}
\usepackage{color}
\begin{document}

%\tracingmacros1

\parindent0pt

\newbox\mybox
\setbox\mybox\hbox{xxxxx}
\hsize \wd\mybox

\rule{\hsize}{1pt}

% x\hspace{\wd\mybox}\leavevmode\linebreak[0]\,y

% x\hspace{\wd\mybox}\leavevmode\allowbreak\,y

xxxx~\leavevmode\linebreak[0]\,y

xxxx~\leavevmode\allowbreak\,y
\showoutput

\end{document}
```

![capture d ecran 2016-10-28 a 12 59 25](https://cloud.githubusercontent.com/assets/2589111/19804405/62054d76-9d0e-11e6-9f61-40c4c1857979.png)

And TeX reports an overfull box for the first line. The second is ok and we can understand what happens looking at  `\showoutput` log trace:

```
...\hbox(4.30554+1.94444)x26.389, glue set - 1.0
....\hbox(0.0+0.0)x0.0
....\OT1/cmr/m/n/10 x
....\OT1/cmr/m/n/10 x
....\OT1/cmr/m/n/10 x
....\OT1/cmr/m/n/10 x
....\penalty 10000
....\penalty 0
....\glue 3.33333 plus 1.66666 minus 1.11111
....\kern 1.66672
....\OT1/cmr/m/n/10 y
....\penalty 10000
....\glue(\parfillskip) 0.0 plus 1.0fil
....\glue(\rightskip) 0.0
...\glue(\parskip) 0.0 plus 1.0
...\glue(\baselineskip) 5.75002
...\hbox(4.30554+0.0)x26.389, glue set 1.16669
....\hbox(0.0+0.0)x0.0
....\OT1/cmr/m/n/10 x
....\OT1/cmr/m/n/10 x
....\OT1/cmr/m/n/10 x
....\OT1/cmr/m/n/10 x
....\penalty 10000
....\glue 3.33333 plus 1.66666 minus 1.11111
....\penalty 0
....\glue(\rightskip) 0.0
```

In the first case the `\penalty 0` was positioned by `\linebreak[0]` before the space, hence immediately after the `\penalty 10000`  coming from the `\nobreak` done by `~`. This means that this `\penalty0` is simply lost. edit: _no wrong, see next comment. But if the break happened there, before the glue, the line would be too underfull (I think...)_

In the second case, it is located after the glue from `~`. Hence a linebreak was possible. There is never overfull nor underfull report. The kern from `\,` disappears at start of next line, before the `y`.

**Comment by jfbu** [comment]
Sorry my explanations are again seemingly wrong. According to TeX by Topic

> Putting more than one penalty in a row is equivalent to putting just the one with
> the minimal value, because that one is the best candidate for line breaking.

Hence possibly the explanation for the non-breaking is that  the line would have been too underfull with `xxxx`. In the second case however the glue is there. But I will stop spamming your site with my sloppy explanations... (once I knew, but I forget things with such non indispensable knowledge...)

**Comment by jfbu** [comment]
There was non underfull report because I had not set the `\hbadness` parameter to zero. But the log is clear:

```
...\hbox(4.30554+0.0)x26.389, glue set 1.16669
```

The space brings `3.3333pt` plus `1.66666` of stretch. But `5pt` is less than the width of `x` (`5.2778pt`). To make the width like `xxxxx` we need to add a stretch of `5.2778-3.3333=1.9445` and this is `1.16669 x 1.66666` up to rounding. Hence the report by TeX. If one adds `\hbadness0\relax` then one does get un underfull report:

```
Underfull \hbox (badness 158) in paragraph at lines 71--73
```

(line numbers differ). The default of `\hbadness` is `1000`. Hence there was no report in the log.

**Comment by wilx** [comment]
I think this is fixed now.
